# -*- coding: utf-8 -*-
"""Session 2 - Simple Summary Statistics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aR-iCOAZGzrGS-DaZ0-XDigV60ObD4L2

#  Use pandas_datareader
"""

from pandas_datareader import data

# Fetch daily data for 4 years
symbols=['AAPL', 'AMZN','GOOGL','FB', 'MCD', 'GM', 'TSLA','PFE']

start_date = '2010-01-01'
end_date = '2021-12-31'

df = data.DataReader(symbols, 'yahoo', start_date, end_date)['Adj Close']
df.head(3)

df.shape

df.FB.plot()

"""# Convert into Rate of Returns"""

returns=(df-df.shift(1))/df.shift(1)

returns.dropna(inplace=True)

returns.head(5)

"""### Or simply uae the pct_change() function"""

df.pct_change().dropna().head(5)

"""## Summary Statistic"""

returns.describe().round(4)

returns.skew()

returns.kurt()

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib notebook
import matplotlib.pyplot as plt
# %matplotlib inline
plt.rcParams["figure.figsize"] = [11, 5]
plt.rcParams["figure.autolayout"] = True

import seaborn as sns
import pandas as pd
import numpy as np

fig, ax = plt.subplots()
fig.set_size_inches(12, 6)
plt.boxplot(returns)
plt.tight_layout()

"""### Histogram """

for sym in returns.columns.values:
    sns.displot(returns[sym], kind='hist', label=sym)
    plt.legend(loc='upper right', fontsize=12)
    plt.xlabel('daily returns')
    plt.show()

"""### Density plot"""

for sym in returns.columns.values:
    sns.displot(returns[sym], kde=True, label=sym)
    plt.legend(loc='upper right', fontsize=12)
    plt.xlabel('daily returns')
import     plt.show()

import scipy


for sym in returns.columns.values:
    _, bins, _ = plt.hist(returns[sym], 200, density=1, alpha=0.5)
    mu, sigma = scipy.stats.norm.fit(returns[sym])
    best_fit_line = scipy.stats.norm.pdf(bins, mu, sigma)
    plt.plot(bins, best_fit_line)
    
    plt.title(f'{sym}  daily returns')
    plt.show()

